name: testing
description: A Flutter app for testing.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.0
  xml: ^6.5.0

dev_dependencies:

  flutter_test:
    sdk: flutter
